import userSampleImage from "../assets/userSampleImage.png";

export const freelancers = [
  {
    id: 1,
    firstName: "Joe",
    secondName: "Bloggs",
    position: ["bartender", "chef"],
    experience: "3 years chef",
    skills: "strong knife skill",
    contract: ["Full-time", "Part-time"],
    postCode: "S13 8RE",
    phoneNumber: "01426243645",
    image: userSampleImage,
    location: { lon: 53.361, lat: -1.3919 },
    aboutYou:
      "Creating new recipes, or adhering to specific food preparation and standards set by the restaurant and local laws.",
  },
  {
    id: 2,
    firstName: "Luna",
    secondName: "Estrada",
    position: ["chef"],
    experience: "0 year hospitality",
    skills: "time management",
    contract: ["Part-time"],
    postCode: "N14 7NR",
    phoneNumber: "01122332142",
    image: userSampleImage,
    location: { lon: 51.62825, lat: -0.13676 },
    aboutYou: "Full-time student looking for part-time on weekend",
  },
  {
    id: 3,
    firstName: "Peter",
    secondName: "Gordon",
    position: ["chef", "bartender"],
    experience: "1 years bartender",
    skills: "bartending",
    contract: ["Full-time"],
    postCode: "SE16 5HL",
    phoneNumber: "09999777766",
    image: userSampleImage,
    location: { lon: 51.50286, lat: -0.03415 },
    aboutYou:
      "I work directly with customers by mixing and serving drink orders. My responsibilities include verifying age requirements, knowing alcohol pairing and tastes, knowing how to make traditional and classy drinks, processing payments, managing inventory and cleaning bar supplies.",
  },
  {
    id: 4,
    firstName: "Beatrice",
    secondName: "Middleton",
    position: ["chef"],
    experience: "7 years kitchen management",
    skills: "management",
    contract: ["Full-time", "Part-time"],
    postCode: "NE1 8BS",
    phoneNumber: "09977996657",
    image: userSampleImage,
    location: { lon: 54.9749, lat: -1.6078 },
    aboutYou:
      "In charge of coordinating and supervising a restaurant's kitchen staff according to food safety standards. My duties include hiring, training and scheduling Cooks, performing quality control on food leaving the kitchen and ordering inventory to keep up with demand",
  },
];

export const jobListings = [
  {
    id: 1,
    currentUserId: 1,
    name: "London Sushi",
    type: "restaurant",
    // position: ["waiter/waitress"],
    salary: "10/hr",
    contract: "partTime",
    postCode: "N4 7HA",
    phoneNumber: "03232435342",
    description:
      "This position is to fill in for a waiter on leave. You will be covering weekend shifts and tuesdays",
  },
  {
    id: 2,
    currentUserId: 1,
    name: "The Red Lion",
    type: "pub",
    // position: ["bartender", "host"],
    salary: "13.5/hr",
    contract: "partTime",
    postCode: "S2 3TR",
    phoneNumber: "09797965565",
    description: "Provide a high level of customer service at all times",
  },
  {
    id: 3,
    currentUserId: 2,
    name: "The Steakhouse",
    type: "restaurant",
    // position: ["host"],
    salary: "11/hr",
    contract: "fullTime",
    postCode: "SE11 5EQ",
    phoneNumber: "04433223344",
    description:
      "Experience of working within, or a desire to work within a high-end restaurant",
  },
  {
    id: 4,
    currentUserId: 3,
    name: "The Kings Head",
    type: "restaurant",
    // position: ["bartender"],
    salary: "12/hr",
    contract: "fullTime",
    postCode: "SE28 0PB",
    phoneNumber: "01234565434",
    description: "40hrs in a week, time slot: 18:00-02:00 / 22:00-06:00",
  },
];

export const businesses = [
  {
    id: 1,
    name: "Burger Queen",
    type: ["takeaway", "restaurant"],
    phoneNumber: "09777657753",
    details: "The most famous burger restaurant in UK",
  },
  {
    id: 2,
    name: "Hey Sushi",
    type: ["restaurant", "hotel"],
    phoneNumber: "06751325534",
    details: "More than 20 stores over London",
  },
  {
    id: 3,
    name: "The Red Lion",
    type: ["pub"],
    phoneNumber: "097567349965",
    details: "A night pub open at 20:00",
  },
];
